### ISSUE TITLE
Upgrading Bitnami OwnCloud from 10.2.1 to 10.3.2

### ISSUE THREAD

**Issue by DimeNZ** [bitnami/bitnami-docker-owncloud#61]
**Description**

Upgrading Bitnami OwnCloud from 10.2.1 to 10.3.2

1. Upgrade-process starts so that OwnCloud is maintenance mode on
2. Disable apps shipped=false
3. /bitnami root folder rights corrected identical with old instance
4.  /bitnami/owncloud/.initialized and .restored writing right to group daemon

**Describe the results you received:**

Everything looks going well but server goes to fail loop and log contains following:

```
app-entrypoint.sh 03:14:25.44 
app-entrypoint.sh 03:14:25.45 Welcome to the Bitnami owncloud container
app-entrypoint.sh 03:14:25.45 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-owncloud
app-entrypoint.sh 03:14:25.45 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-owncloud/issues
app-entrypoint.sh 03:14:25.46 Send us your feedback at containers@bitnami.com
app-entrypoint.sh 03:14:25.46 
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/tmp"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/tmp
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/logs"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/logs
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/var","/opt/bitnami/php/var/log","/opt/bitnami/php/var/run"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/log
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/run
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing owncloud
ownclou DEBUG Preparing Apache environment...
apache  TRACE Skipping reload: com.bitnami.apache not running
ownclou DEBUG Preparing PHP environment...
ownclou TRACE [restorePersistedData] Restoring /bitnami/owncloud/conf to /opt/bitnami/owncloud/conf
ownclou TRACE [restorePersistedData] Restoring /bitnami/owncloud/data to /opt/bitnami/owncloud/data
ownclou TRACE [restorePersistedData] Restoring /bitnami/owncloud/assets to /opt/bitnami/owncloud/assets
ownclou TRACE [restorePersistedData] Restoring /bitnami/owncloud/apps-external to /opt/bitnami/owncloud/apps-external
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,status,--no-warnings,--output,json
ownclou INFO  New ownCloud version detected
ownclou INFO  Minor version detected, starting upgrade process...
ownclou DEBUG Enabling Maintenance mode...
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,maintenance:mode,--on
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,app:list,--no-warnings,--output,json
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,app:list,--no-warnings,--shipped=false,--output,json
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,config:list,--no-warnings,--output,json
ownclou DEBUG Disabling app: files_mediaviewer...
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,app:disable,files_mediaviewer,--no-warnings
ownclou DEBUG Running upgrade...
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,upgrade,--no-warnings
Error executing 'postInstallation': Program exited with exit code 2
nami    TRACE Error: Error executing 'postInstallation': Program exited with exit code 2
    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.php/helpers.js:69:14)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at Object.$app.helpers.executeOcc (/root/.nami/components/com.bitnami.owncloud/helpers.js:60:22)
    at Object.$app.helpers.upgradeDatabase (/root/.nami/components/com.bitnami.owncloud/helpers.js:151:20)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.owncloud/main.js:54:16)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32) 
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348) 
```

**Describe the results you expected:**

- Previous upgrading from 10.1.x to 10.2.1 with similar procedure was succesful.

Azure Kubernetes Service

**Comment by juan131** [comment]
Hi @DimeNZ 

Could you try to perform the upgrade process version by version? I mean:

- Upgrade from `bitnami/owncloud: 10.2.1` to `bitnami/owncloud: 10.3.0`
- Then, upgrade from `bitnami/owncloud: 10.3.0` to `bitnami/owncloud: 10.3.1`
- Finally, upgrade from `bitnami/owncloud: 10.3.1` to `bitnami/owncloud: 10.3.2`
